name: SmileApp
#description: Medico_APp
description: SmileApp

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  #sdk: ">=2.2.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  font_awesome_flutter:
  flutter_swiper: ^1.1.6
  carousel_slider: ^4.0.0
  titled_navigation_bar: ^4.1.0
  flutter_svg: ^1.0.3
  curved_navigation_bar: ^1.0.3
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.1
  meta: ^1.7.0
  intl: ^0.17.0
  # Smile Detection
  google_mlkit_face_detection: ^0.4.0
  image_picker: ^0.8.5+3
  camera: ^0.10.0
  camera_android: ^0.10.0
  camera_avfoundation: ^0.9.8+2
  shared_preferences: ^2.0.6
  circular_countdown_timer: ^0.2.2
  glassmorphism: ^3.0.0
  syncfusion_flutter_maps: ^20.2.50
  rating_dialog: ^2.0.4
  # State management with flutter Redux
  flutter_redux: ^0.10.0
  # Animated Text
  animated_text_kit: ^4.2.1
  # Notification
  firebase_core: ^1.10.0
  # firebase_messaging: ^13.0.1
  firebase_messaging: ^11.2.5
  # Setup Icon
  flutter_launcher_icons: "^0.10.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo1.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/custom/mytribe.jpg
    - images/custom/pucketbuddy.jpg
    - images/custom/smilegram.jpg
    - images/custom/gift.png
    - images/custom/giftopen.png
    - images/custom/giftopen1.png
    - assets/world_map.json
    - assets/logo1.jpeg
    - images/image-home.jpeg
    - images/facebook-fill.png
    - images/google-fill.png
    - images/cellphone-line.png
    - images/verification.png
    - images/Image23.png
    - images/f1.png
    - images/f-1.png
    - images/undraw_alien_science_nonm.png
    - images/microscope.png
    - images/pill.png
    - images/nurse.png
    - images/doctor-productivity.jpg
    - images/13nov_resize.jpg
    - images/medical-lab-technician-85654102.jpg
    - images/asset-1.png
    - images/asset-1a.jpeg
    - images/asset-2.png
    - images/asset-2a.jpeg
    - images/asset-3.png
    - images/asset-3a.jpeg
    - images/asset-4.png
    - images/asset-4a.jpeg
    - images/asset-5.png
    - images/asset-5a.jpeg
    - images/asset-6.png
    - images/asset-6a.jpeg
    - images/Image 11.png
    - images/Image 12.png
    - images/Image 19.png
    - images/index.jpeg
    - images/imageuser.png
    - images/gps.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900


